export const BLOCKS = {
  grass: { name: "草方块", color: 0x62a444, hardness: 0.65, drop: "dirt" },
  dirt: { name: "泥土", color: 0x79533a, hardness: 0.5 },
  stone: {
    name: "石头",
    color: 0x85888b,
    hardness: 1.7,
    tool: "pickaxe",
    drop: "cobble",
  },
  cobble: { name: "圆石", color: 0x65696c, hardness: 1.5, tool: "pickaxe" },
  sand: { name: "沙子", color: 0xd9ca86, hardness: 0.5 },
  sandstone: { name: "砂岩", color: 0xc8b875, hardness: 0.9, tool: "pickaxe" },
  log: { name: "橡木原木", color: 0x68472d, hardness: 1.2, tool: "axe" },
  leaves: { name: "树叶", color: 0x357438, hardness: 0.2, transparent: true },
  planks: { name: "橡木板", color: 0xa77b45, hardness: 1, tool: "axe" },
  water: {
    name: "水",
    color: 0x287fca,
    hardness: 99,
    liquid: true,
    transparent: true,
  },
  ice: { name: "冰", color: 0xa9dbeb, hardness: 0.5, transparent: true },
  snow: { name: "雪", color: 0xefffff, hardness: 0.25 },
  clay: { name: "黏土", color: 0x8c919d, hardness: 0.6 },
  gravel: { name: "沙砾", color: 0x78726e, hardness: 0.6 },
  coal_ore: {
    name: "煤矿石",
    color: 0x484a4b,
    hardness: 2,
    tool: "pickaxe",
    drop: "coal",
  },
  iron_ore: {
    name: "铁矿石",
    color: 0xa88470,
    hardness: 2.5,
    tool: "stone_pickaxe",
    drop: "raw_iron",
  },
  gold_ore: {
    name: "金矿石",
    color: 0xc9a93d,
    hardness: 3,
    tool: "iron_pickaxe",
  },
  diamond_ore: {
    name: "钻石矿石",
    color: 0x48c8c2,
    hardness: 3,
    tool: "iron_pickaxe",
  },
  coral_red: { name: "红珊瑚", color: 0xe24e69, hardness: 0.3 },
  coral_blue: { name: "蓝珊瑚", color: 0x477bd8, hardness: 0.3 },
  coral_yellow: { name: "黄珊瑚", color: 0xf0cc42, hardness: 0.3 },
  kelp: { name: "海带", color: 0x2c885d, hardness: 0.1, transparent: true },
  seagrass: { name: "海草", color: 0x45a66d, hardness: 0.1, transparent: true },
  glass: { name: "玻璃", color: 0xc7e4e5, hardness: 0.4, transparent: true },
  brick: { name: "砖块", color: 0x9f4e3e, hardness: 1.8, tool: "pickaxe" },
  obsidian: {
    name: "黑曜石",
    color: 0x29213a,
    hardness: 8,
    tool: "diamond_pickaxe",
  },
  bedrock: { name: "基岩", color: 0x242627, hardness: 999 },
  crafting_table: {
    name: "工作台",
    color: 0x9b6635,
    hardness: 1.5,
    tool: "axe",
  },
  furnace: { name: "熔炉", color: 0x55585a, hardness: 2, tool: "pickaxe" },
  chest: { name: "箱子", color: 0xb9772f, hardness: 1.5, tool: "axe" },
  bed: { name: "床", color: 0xb83737, hardness: 0.4 },
  torch: { name: "火把", color: 0xffb629, hardness: 0.1, transparent: true },
  farmland: { name: "耕地", color: 0x68452f, hardness: 0.5 },
  wheat: { name: "小麦", color: 0xd8bc45, hardness: 0.1, transparent: true },
  carrot: {
    name: "胡萝卜",
    color: 0xe9812d,
    hardness: 0.1,
    transparent: true,
    food: 3,
  },
  potato: {
    name: "马铃薯",
    color: 0xb99345,
    hardness: 0.1,
    transparent: true,
    food: 2,
  },
  shipwood: { name: "沉船木", color: 0x4e3425, hardness: 1.8, tool: "axe" },
  prismarine: { name: "海晶石", color: 0x58a797, hardness: 2, tool: "pickaxe" },
  treasure: {
    name: "宝藏箱",
    color: 0xf1bd4d,
    hardness: 2,
    tool: "axe",
    drop: "treasure_map",
  },
  wool: { name: "白色羊毛", color: 0xe4e1d5, hardness: 0.4 },
  cactus: { name: "仙人掌", color: 0x3d873e, hardness: 0.4 },
  pumpkin: { name: "南瓜", color: 0xd77c22, hardness: 0.6, tool: "axe" },
};

export const ITEMS = {
  stick: { name: "木棍" },
  coal: { name: "煤炭" },
  raw_iron: { name: "粗铁" },
  iron_ingot: { name: "铁锭" },
  bread: { name: "面包", food: 5 },
  boat: { name: "橡木船" },
  bucket: { name: "桶" },
  fish_bucket: { name: "鳕鱼桶" },
  bow: { name: "弓", durability: 96 },
  arrow: { name: "箭" },
  armor: { name: "铁胸甲", armor: 6, durability: 240 },
  trident: { name: "三叉戟", damage: 8, durability: 250 },
  treasure_map: { name: "藏宝线索" },
  wheat_seed: { name: "小麦种子" },
  wooden_pickaxe: { name: "木镐", tool: "pickaxe", tier: 1, durability: 59 },
  stone_pickaxe: { name: "石镐", tool: "pickaxe", tier: 2, durability: 131 },
  iron_pickaxe: { name: "铁镐", tool: "pickaxe", tier: 3, durability: 250 },
  wooden_axe: { name: "木斧", tool: "axe", tier: 1, durability: 59 },
  wooden_hoe: { name: "木锄", tool: "hoe", tier: 1, durability: 59 },
};

export const RECIPES = [
  { id: "planks", name: "木板 ×4", in: { log: 1 }, out: { planks: 4 } },
  { id: "stick", name: "木棍 ×4", in: { planks: 2 }, out: { stick: 4 } },
  {
    id: "crafting_table",
    name: "工作台",
    in: { planks: 4 },
    out: { crafting_table: 1 },
  },
  {
    id: "wooden_pickaxe",
    name: "木镐",
    in: { planks: 3, stick: 2 },
    out: { wooden_pickaxe: 1 },
  },
  {
    id: "stone_pickaxe",
    name: "石镐",
    in: { cobble: 3, stick: 2 },
    out: { stone_pickaxe: 1 },
  },
  {
    id: "iron_pickaxe",
    name: "铁镐",
    in: { iron_ingot: 3, stick: 2 },
    out: { iron_pickaxe: 1 },
  },
  {
    id: "torch",
    name: "火把 ×4",
    in: { coal: 1, stick: 1 },
    out: { torch: 4 },
  },
  { id: "chest", name: "箱子", in: { planks: 8 }, out: { chest: 1 } },
  { id: "furnace", name: "熔炉", in: { cobble: 8 }, out: { furnace: 1 } },
  { id: "boat", name: "船", in: { planks: 5 }, out: { boat: 1 } },
  { id: "bucket", name: "桶", in: { iron_ingot: 3 }, out: { bucket: 1 } },
  { id: "bread", name: "面包", in: { wheat: 3 }, out: { bread: 1 } },
  { id: "bed", name: "床", in: { planks: 3, wool: 3 }, out: { bed: 1 } },
  {
    id: "wooden_hoe",
    name: "木锄",
    in: { planks: 2, stick: 2 },
    out: { wooden_hoe: 1 },
  },
  { id: "bow", name: "弓", in: { stick: 3, wool: 3 }, out: { bow: 1 } },
  { id: "armor", name: "铁胸甲", in: { iron_ingot: 8 }, out: { armor: 1 } },
  {
    id: "trident",
    name: "三叉戟",
    in: { prismarine: 4, iron_ingot: 2 },
    out: { trident: 1 },
  },
];

export const ALL_DEFINITIONS = { ...BLOCKS, ...ITEMS };
export const HOTBAR_DEFAULT = [
  "wooden_pickaxe",
  "grass",
  "stone",
  "planks",
  "sand",
  "torch",
  "crafting_table",
  "bucket",
  "trident",
];
