import * as THREE from 'three';
import './style.css';
import {BLOCKS,ITEMS,ALL_DEFINITIONS,HOTBAR_DEFAULT,RECIPES} from './data.js';
import {SEA_LEVEL,hashSeed,noise2,biomeAt,terrainHeight,generatedBlock,keyOf,Inventory,canHarvest,breakSeconds,tickSurvival,serializeSave,parseSave} from './sim.js';

const $=s=>document.querySelector(s); const canvas=$('#game');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x79b7dc); scene.fog=new THREE.Fog(0x91bdd0,25,76);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,120); camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=false;
scene.add(new THREE.HemisphereLight(0xc8eaff,0x5b6455,1.9)); const sun=new THREE.DirectionalLight(0xfff3d0,2); sun.position.set(35,50,20); scene.add(sun);
const worldGroup=new THREE.Group(); const entityGroup=new THREE.Group(); const dropsGroup=new THREE.Group(); scene.add(worldGroup,entityGroup,dropsGroup);
const boxGeo=new THREE.BoxGeometry(1,1,1); const raycaster=new THREE.Raycaster(); raycaster.far=6; const center=new THREE.Vector2(0,0);
const outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.012,1.012,1.012)),new THREE.LineBasicMaterial({color:0x111111})); outline.visible=false; scene.add(outline);

let seedText='tidalcraft',seed=hashSeed(seedText),started=false,selected=0,last=performance.now(),lastHud=0,yaw=0,pitch=0,frameTimes=[],saveTimer=0,breakState=null;
let modifications=new Map(),blockMeshes=[],entities=[],drops=[],keys={},chunks=new Set(),difficulty='normal';
let player={x:0,y:15,z:0,vx:0,vy:0,vz:0,health:20,hunger:20,oxygen:10,onGround:false,time:6000,spawn:{x:0,y:15,z:0},dead:false};
let inventory=new Inventory(); HOTBAR_DEFAULT.forEach((id,i)=>inventory.slots[i]={id,count:id==='wooden_pickaxe'||id==='trident'?1:32,durability:ITEMS[id]?.durability}); inventory.add('bread',5); inventory.add('arrow',16);

function materialFor(id){const d=BLOCKS[id];return new THREE.MeshLambertMaterial({color:d.color,transparent:!!d.transparent,opacity:id==='water' ? .62 : (d.transparent ? .82 : 1),depthWrite:id!=='water',flatShading:true})}
const materials=new Map(Object.keys(BLOCKS).map(id=>[id,materialFor(id)]));
function actualBlock(x,y,z){const k=keyOf(x,y,z);return modifications.has(k)?modifications.get(k):generatedBlock(Math.floor(x),Math.floor(y),Math.floor(z),seed)}
function buildWorld(){while(worldGroup.children.length)worldGroup.remove(worldGroup.children[0]);blockMeshes=[];chunks.clear();const px=Math.floor(player.x/16),pz=Math.floor(player.z/16);const byType={};for(let cz=pz-2;cz<=pz+2;cz++)for(let cx=px-2;cx<=px+2;cx++){chunks.add(`${cx},${cz}`);for(let z=cz*16;z<cz*16+16;z++)for(let x=cx*16;x<cx*16+16;x++){const h=terrainHeight(x,z,seed);for(let y=Math.max(0,h-3);y<=Math.max(h,SEA_LEVEL);y++){const id=actualBlock(x,y,z);if(!id)continue;(byType[id]??=[]).push({x,y,z})}addFeature(byType,x,h,z)}}for(const [id,poses]of Object.entries(byType)){const mesh=new THREE.InstancedMesh(boxGeo,materials.get(id),poses.length);const o=new THREE.Object3D();poses.forEach((p,i)=>{o.position.set(p.x,p.y,p.z);o.updateMatrix();mesh.setMatrixAt(i,o.matrix)});mesh.userData={id,poses};mesh.instanceMatrix.needsUpdate=true;worldGroup.add(mesh);blockMeshes.push(mesh)}$('#world-label').textContent=`${seedText} · ${chunks.size} chunks`}
function add(by,id,x,y,z){(by[id]??=[]).push({x,y,z})}
function addFeature(by,x,h,z){const b=biomeAt(x,z,seed),n=noise2(x,z,seed+500);if(b==='forest'&&n>.992){for(let y=1;y<5;y++)add(by,'log',x,h+y,z);for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)if(Math.abs(dx)+Math.abs(dz)<4)add(by,'leaves',x+dx,h+4+(Math.abs(dx)+Math.abs(dz)<2?1:0),z+dz)}if(b==='desert'&&n>.995)for(let y=1;y<4;y++)add(by,'cactus',x,h+y,z);if(b.includes('ocean')&&n>.988){const id=b==='warm_ocean'?['coral_red','coral_blue','coral_yellow'][Math.floor(n*100)%3]:'kelp';for(let y=h+1;y<Math.min(SEA_LEVEL,h+4);y++)add(by,id,x,y,z)}if(b==='frozen_ocean'&&n>.994)for(let y=SEA_LEVEL+1;y<SEA_LEVEL+5;y++)add(by,'ice',x,y,z);if(b==='ocean'&&n>.9985){for(let dx=-3;dx<=3;dx++)add(by,'shipwood',x+dx,h+1,z);add(by,'treasure',x,h+2,z)}if(b==='deep_ocean'&&n>.998){for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)if(Math.abs(dx)===2||Math.abs(dz)===2)add(by,'prismarine',x+dx,h+1,z+dz)}}

function spawnEntities(){while(entityGroup.children.length)entityGroup.remove(entityGroup.children[0]);entities=[];const types=['pig','cow','sheep','chicken','zombie','spider','creeper','dolphin','cod','salmon','tropical_fish','pufferfish'];for(let i=0;i<30;i++){const a=noise2(i,7,seed)*Math.PI*2,r=8+noise2(i,8,seed)*28,x=player.x+Math.cos(a)*r,z=player.z+Math.sin(a)*r,b=biomeAt(x,z,seed),aquatic=b.includes('ocean');let type=types[(i+seed)%types.length];if(aquatic)type=types[7+(i%5)];else if(type.includes('fish')||type==='dolphin')type=types[i%7];const hostile=['zombie','spider','creeper'].includes(type);const colors={pig:0xe79a9a,cow:0x634434,sheep:0xe8e5db,chicken:0xe8e8df,zombie:0x4d8d55,spider:0x342b2a,creeper:0x56a949,dolphin:0x6995a5,cod:0x9a7951,salmon:0xb76150,tropical_fish:0xf4b64d,pufferfish:0xb9a24a};const geo=new THREE.BoxGeometry(type==='chicken'?.6:type.includes('fish')?1.1:1,type==='spider'?.45:type.includes('fish')?.55:1.2,type==='spider'?1.3:.65),m=new THREE.MeshLambertMaterial({color:colors[type]});const mesh=new THREE.Mesh(geo,m);const y=aquatic?Math.max(2,SEA_LEVEL-2):terrainHeight(x,z,seed)+1;mesh.position.set(x,y,z);entityGroup.add(mesh);entities.push({type,hostile,mesh,hp:hostile?12:8,phase:i,speed:.4+noise2(i,2,seed)*.5})}}
function updateEntities(dt){const night=player.time>13000&&player.time<23000;for(const e of entities){const dx=player.x-e.mesh.position.x,dz=player.z-e.mesh.position.z,dist=Math.hypot(dx,dz),aquatic=['dolphin','cod','salmon','tropical_fish','pufferfish'].includes(e.type);if(e.hostile&&night&&dist<14){e.mesh.position.x+=dx/dist*e.speed*dt;e.mesh.position.z+=dz/dist*e.speed*dt;if(dist<1.4&&difficulty!=='peaceful'){player.health-=dt*(difficulty==='hard'?2:1);if(e.type==='creeper'&&dist<1.1)explode(e)}}else{e.phase+=dt*.5;e.mesh.position.x+=Math.cos(e.phase)*e.speed*dt*.25;e.mesh.position.z+=Math.sin(e.phase)*e.speed*dt*.25}if(aquatic)e.mesh.position.y=SEA_LEVEL-2+Math.sin(e.phase*2);else e.mesh.position.y=terrainHeight(e.mesh.position.x,e.mesh.position.z,seed)+.8;if(e.type==='pufferfish')e.mesh.scale.setScalar(dist<3?1.5:1);if(e.type==='zombie'&&!night)e.mesh.material.emissive.setHex(0x5b2100)}}
function explode(e){const p=e.mesh.position;for(let x=-2;x<=2;x++)for(let y=-1;y<=2;y++)for(let z=-2;z<=2;z++)if(x*x+y*y+z*z<6)modifications.set(keyOf(p.x+x,p.y+y,p.z+z),null);entityGroup.remove(e.mesh);entities=entities.filter(v=>v!==e);player.health-=5;toast('爬行者爆炸改变了地形');buildWorld()}

function collides(x,y,z){const r=.3;for(const dx of[-r,r])for(const dz of[-r,r])for(const dy of[0,.9,1.75]){const id=actualBlock(Math.floor(x+dx+.5),Math.floor(y+dy+.5),Math.floor(z+dz+.5));if(id&&!BLOCKS[id]?.liquid&&!BLOCKS[id]?.transparent)return true}return false}
function updatePlayer(dt){const underwater=player.y<SEA_LEVEL-.2&&actualBlock(player.x,player.y+1,player.z)==='water';const speed=(keys.ShiftLeft?7.2:keys.KeyC?2.1:4.3)*(underwater?.72:1),fwd=(keys.KeyW?1:0)-(keys.KeyS?1:0),side=(keys.KeyD?1:0)-(keys.KeyA?1:0);const len=Math.hypot(fwd,side)||1,sy=Math.sin(yaw),cy=Math.cos(yaw);player.vx=((side*cy-fwd*sy)/len)*speed;player.vz=((fwd*cy+side*sy)/len)*speed;if(underwater){player.vy+=(keys.Space?8:-1.4)*dt;player.vy*=.9}else player.vy-=22*dt;if(keys.Space&&player.onGround){player.vy=8;player.onGround=false}let nx=player.x+player.vx*dt;if(!collides(nx,player.y,player.z))player.x=nx;else if(!collides(nx,player.y+.55,player.z))player.y+=.55,player.x=nx;let nz=player.z+player.vz*dt;if(!collides(player.x,player.y,nz))player.z=nz;let ny=player.y+player.vy*dt;if(!collides(player.x,ny,player.z)){player.y=ny;player.onGround=false}else{if(player.vy<0)player.onGround=true;player.vy=0}if(player.y<0){damage(99);respawn()}tickSurvival(player,dt,{underwater,difficulty});$('#underwater').style.opacity=underwater?1:0;$('#oxygen-row').style.display=underwater?'block':'none';camera.position.set(player.x,player.y+1.62-(keys.KeyC?.35:0),player.z);camera.rotation.set(pitch,yaw,0);if(player.health<=0&&!player.dead){player.dead=true;for(const s of inventory.slots)if(s)spawnDrop(player.x,player.y+1,player.z,s.id,s.count);inventory=new Inventory();toast('你死了 — 正在重生');setTimeout(respawn,1700)}if(Math.floor(player.x/16)+','+Math.floor(player.z/16)!==[...chunks][12]){const edge=[...chunks].every(c=>{const[a,b]=c.split(',').map(Number);return Math.abs(a-Math.floor(player.x/16))<=2&&Math.abs(b-Math.floor(player.z/16))<=2});if(!edge)buildWorld()}}
function damage(n){player.health=Math.max(0,player.health-n)} function respawn(){Object.assign(player,{...player.spawn,vx:0,vy:0,vz:0,health:20,hunger:20,oxygen:10,dead:false})}
function spawnDrop(x,y,z,id,count=1){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.28,.28,.28),new THREE.MeshLambertMaterial({color:BLOCKS[id]?.color||0xf3d26b}));mesh.position.set(x,y,z);dropsGroup.add(mesh);drops.push({mesh,id,count,age:0})}
function updateDrops(dt){for(const d of drops){d.age+=dt;d.mesh.rotation.y+=dt*2;d.mesh.position.y+=Math.sin(d.age*3)*.001;const dist=d.mesh.position.distanceTo(camera.position);if(dist<1.7){const left=inventory.add(d.id,d.count);if(!left){dropsGroup.remove(d.mesh);drops=drops.filter(x=>x!==d);toast(`拾取 ${ALL_DEFINITIONS[d.id]?.name||d.id}`);renderHud()}}}}

function target(){raycaster.setFromCamera(center,camera);const hits=raycaster.intersectObjects([...blockMeshes,...entityGroup.children],false);return hits[0]}
function actPlace(){const hit=target();if(!hit||entityGroup.children.includes(hit.object))return;const p=hit.point.clone().add(hit.face.normal.clone().multiplyScalar(.51)).floor();const slot=inventory.slots[selected];if(!slot||!BLOCKS[slot.id]||BLOCKS[slot.id].liquid)return toast('选择一个可放置方块');if(collides(p.x,p.y,p.z)||Math.hypot(p.x-player.x,p.z-player.z)<.7&&Math.abs(p.y-player.y)<2)return toast('此处不能放置');modifications.set(keyOf(p.x,p.y,p.z),slot.id);slot.count--;if(!slot.count)inventory.slots[selected]=null;buildWorld();renderHud()}
function startBreak(){const hit=target();if(!hit)return;const ent=entities.find(e=>e.mesh===hit.object);if(ent){attack(ent);return}const pos=hit.object.userData.poses[hit.instanceId];if(!pos)return;const id=actualBlock(pos.x,pos.y,pos.z);if(id==='water'||id==='bedrock')return;breakState={pos,id,start:performance.now(),duration:breakSeconds(id,inventory.slots[selected]?.id)*1000}}
function finishBreak(){if(!breakState)return;const elapsed=performance.now()-breakState.start;if(elapsed>=breakState.duration){const{id,pos}=breakState,item=inventory.slots[selected]?.id;modifications.set(keyOf(pos.x,pos.y,pos.z),null);if(canHarvest(id,item)){const drop=BLOCKS[id].drop||id;spawnDrop(pos.x,pos.y+.3,pos.z,drop)}if(inventory.slots[selected]?.durability){inventory.slots[selected].durability--;if(inventory.slots[selected].durability<=0){inventory.slots[selected]=null;toast('工具损坏')}}buildWorld();renderHud()}breakState=null}
function attack(e){const slot=inventory.slots[selected],damage=slot?.id==='trident'?8:slot?.id?.includes('axe')?6:2;e.hp-=damage;e.mesh.material.emissive.setHex(0xffffff);setTimeout(()=>e.mesh?.material?.emissive?.setHex(0),90);e.mesh.position.add(new THREE.Vector3(e.mesh.position.x-player.x,.2,e.mesh.position.z-player.z).normalize().multiplyScalar(.7));if(e.hp<=0){spawnDrop(e.mesh.position.x,e.mesh.position.y,e.mesh.position.z,e.type==='sheep'?'wool':e.type.includes('fish')?'bread':'raw_iron',1);entityGroup.remove(e.mesh);entities=entities.filter(x=>x!==e);toast(`${e.type} 被击败`)}}

function renderHud(){const pips=(n,max,klass='')=>Array.from({length:max},(_,i)=>`<span class="pip ${klass} ${i>=Math.ceil(n/2)?'off':''}">♥</span>`).join('');$('#health').innerHTML=pips(player.health,10);$('#hunger').innerHTML=pips(player.hunger,10,'food');$('#oxygen').innerHTML=pips(player.oxygen*2,10,'oxygen');$('#hotbar').innerHTML=inventory.slots.slice(0,9).map((s,i)=>`<button class="slot ${i===selected?'selected':''}" data-slot="${i}">${s?`<span class="cube-icon" style="background:#${(BLOCKS[s.id]?.color||0x9b9b9b).toString(16).padStart(6,'0')}"></span><small>${s.count}</small><em>${i+1}</em>${s.durability?`<span class="durability"><i style="width:${s.durability/(ITEMS[s.id].durability||1)*100}%"></i></span>`:''}`:`<em>${i+1}</em>`}</button>`).join('');document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{selected=+b.dataset.slot;renderHud()});const s=inventory.slots[selected];$('#held').style.background=`#${(BLOCKS[s?.id]?.color||0x6d7479).toString(16).padStart(6,'0')}`;renderInventory()}
function renderInventory(){$('#inventory').innerHTML=inventory.slots.map(s=>`<div class="inv-slot">${s?`<span>${ALL_DEFINITIONS[s.id]?.name||s.id}</span><b>${s.count}</b>`:''}</div>`).join('');$('#recipes').innerHTML=RECIPES.map((r,i)=>`<button class="recipe" data-recipe="${i}" ${inventory.canCraft(r)?'':'disabled'}><span>${r.name}<small>${Object.entries(r.in).map(([id,n])=>`${ALL_DEFINITIONS[id]?.name||id}×${n}`).join(' · ')}</small></span><b>制作</b></button>`).join('');document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>{if(inventory.craft(RECIPES[+b.dataset.recipe])){toast(`已制作 ${RECIPES[+b.dataset.recipe].name}`);renderHud()}})}
function updateTarget(){const h=target();if(!h){outline.visible=false;$('#target-label').textContent='';return}const ent=entities.find(e=>e.mesh===h.object);if(ent){outline.visible=false;$('#target-label').textContent=ent.type;return}const p=h.object.userData.poses[h.instanceId];if(!p)return;outline.visible=true;outline.position.set(p.x,p.y,p.z);const id=actualBlock(p.x,p.y,p.z),progress=breakState?Math.min(100,(performance.now()-breakState.start)/breakState.duration*100):0;$('#target-label').textContent=`${BLOCKS[id]?.name||id}${breakState?` ${progress|0}%`:''}`}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}

function save(){const data=serializeSave({seed,seedText,player,inventory,modifications:[...modifications],difficulty,entities:entities.map(e=>({type:e.type,x:e.mesh.position.x,y:e.mesh.position.y,z:e.mesh.position.z,hp:e.hp}))});localStorage.setItem('tidalcraft-save-v1',data);toast('世界已保存')}
function load(){const raw=localStorage.getItem('tidalcraft-save-v1');if(!raw)return false;const d=parseSave(raw);if(!d){$('#load-note').textContent='存档损坏，已安全回退；可创建新世界。';return false}seed=d.seed;seedText=d.seedText||String(seed);player=d.player;inventory=d.inventory;modifications=new Map(d.modifications||[]);difficulty=d.difficulty||'normal';$('#seed').value=seedText;$('#load-note').textContent='发现本地存档，将从上次位置继续。';return true}
function begin(fresh=false){if(fresh){localStorage.removeItem('tidalcraft-save-v1');seedText=$('#seed').value||'aquatic-140';seed=hashSeed(seedText);modifications=new Map();player={x:0,y:terrainHeight(0,0,seed)+3,z:0,vx:0,vy:0,vz:0,health:20,hunger:20,oxygen:10,onGround:false,time:6000,spawn:{x:0,y:terrainHeight(0,0,seed)+3,z:0},dead:false};inventory=new Inventory();HOTBAR_DEFAULT.forEach((id,i)=>inventory.slots[i]={id,count:id==='wooden_pickaxe'||id==='trident'?1:32,durability:ITEMS[id]?.durability});inventory.add('bread',5);inventory.add('arrow',16)}else if(!localStorage.getItem('tidalcraft-save-v1')){seedText=$('#seed').value;seed=hashSeed(seedText);player.y=terrainHeight(0,0,seed)+3;player.spawn.y=player.y}buildWorld();spawnEntities();renderHud();$('#menu').classList.add('hidden');started=true;canvas.requestPointerLock()}

function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;if(started&&!player.dead){updatePlayer(dt);updateEntities(dt);updateDrops(dt);updateTarget();player.time=(player.time+dt*20)%24000;const angle=(player.time/24000)*Math.PI*2-Math.PI/2;sun.position.set(Math.cos(angle)*50,Math.sin(angle)*50,20);sun.intensity=Math.max(.12,Math.sin(angle)*1.8);const daylight=Math.max(.08,(Math.sin(angle)+.25)/1.25);scene.background.setRGB(.12+.35*daylight,.18+.48*daylight,.25+.55*daylight);scene.fog.color.copy(scene.background);frameTimes.push(dt*1000);if(frameTimes.length>300)frameTimes.shift();if(now-lastHud>200){lastHud=now;$('#fps').textContent=`FPS ${Math.round(1000/(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length||16))}`;$('#coords').textContent=`XYZ ${player.x.toFixed(1)} / ${player.y.toFixed(1)} / ${player.z.toFixed(1)}`;$('#clock').textContent=`Day 1 · ${String((Math.floor(player.time/1000)+6)%24).padStart(2,'0')}:00`;$('#biome').textContent=biomeAt(player.x,player.z,seed).replaceAll('_',' ');renderHud()}saveTimer+=dt;if(saveTimer>30){saveTimer=0;save()}}renderer.render(scene,camera)}

window.__tidalcraft={snapshot:()=>{const sorted=[...frameTimes].sort((a,b)=>a-b),avg=frameTimes.reduce((a,b)=>a+b,0)/(frameTimes.length||1);return {started,chunks:chunks.size,blockTypes:blockMeshes.length,instances:blockMeshes.reduce((n,m)=>n+m.count,0),entities:entities.length,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,averageFps:1000/avg,p95FrameMs:sorted[Math.floor(sorted.length*.95)]||0,samples:frameTimes.length}}};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.code]=true;if(/^Digit[1-9]$/.test(e.code)){selected=+e.code.at(-1)-1;renderHud()}if(e.code==='KeyE'){const open=$('#panel').classList.toggle('hidden');document.body.classList.toggle('panel-open',!open);if(!open)document.exitPointerLock();else canvas.requestPointerLock()}if(e.code==='KeyQ'){const s=inventory.slots[selected];if(s){spawnDrop(player.x,player.y+1,player.z,s.id,1);s.count--;if(!s.count)inventory.slots[selected]=null;renderHud()}}});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){yaw-=e.movementX*.0022;pitch=Math.max(-Math.PI/2+.02,Math.min(Math.PI/2-.02,pitch-e.movementY*.0022))}});canvas.addEventListener('mousedown',e=>{if(document.pointerLockElement!==canvas)return canvas.requestPointerLock();if(e.button===0)startBreak();if(e.button===2)actPlace()});canvas.addEventListener('mouseup',e=>{if(e.button===0)finishBreak()});canvas.addEventListener('contextmenu',e=>e.preventDefault());$('#play').onclick=()=>begin(false);$('#new-world').onclick=()=>begin(true);$('#save-btn').onclick=save;$('#close-panel').onclick=()=>{document.body.classList.remove('panel-open');$('#panel').classList.add('hidden');canvas.requestPointerLock()};load();requestAnimationFrame(animate);
